# Generated by Django 5.0.1 on 2024-01-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birth', models.DateField()),
                ('position', models.CharField(choices=[('Director', 'Director'), ('Sound designer', 'Sound designer'), ('Assistant Director', 'Assistant Director'), ('Producer', 'Producer'), ('Production Assistant', 'Production Assistant'), ('Makeup artist', 'Makeup artist'), ('Camera operator', 'Camera operator'), ('Script supervisor', 'Script supervisor')], max_length=200)),
                ('joined', models.DateField(auto_now=True)),
            ],
        ),
    ]
