# Generated by Django 5.0.1 on 2024-01-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
