# Generated by Django 5.0.1 on 2024-01-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_joined'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='employees',
            field=models.ManyToManyField(related_name='employees', to='employees.employee'),
        ),
    ]
