# Generated by Django 5.0.1 on 2024-01-14 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_joined'),
        ('movies', '0004_alter_movies_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='employees',
        ),
        migrations.AddField(
            model_name='movies',
            name='employees',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='employees.employee'),
            preserve_default=False,
        ),
    ]
